In [10]:
# Csomag importálás

library(tidyverse)
library(recipes)
library(lubridate)

In [11]:
# sacramento = read_csv("out.csv", col_types=list(beds = col_integer(), 
#                                                             baths = col_integer(), 
#                                                             sq__ft = col_integer(), 
#                                                             price = col_integer(),
#                                                             type = col_factor(),
#                                                             zip = col_integer() ))

df = read_csv("./../data/apartment_data.csv")
# problems(df)

head(df, 2)

Warning message:
"One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat)"
Rows: 99826 Columns: 21
── Column specification ───────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (13): category, title, body, amenities, currency, fee, has_photo, pets_a...
dbl  (8): bathrooms, bedrooms, price, price_display, square_feet, latitude, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  category               title
1 housing/rent/apartment One BR 507 & 509 Esplanade
2 housing/rent/apartment Three BR 146 Lochview Drive
  body
1 This unit is located at 507 & 509 Esplanade, Redondo Beach, 90277, CAMonthly rental rates range from $2195We have 1 beds units available for rent
2 This unit is located at 146 Lochview Drive, Newport News, 23602, VAMonthly rental rates range from $1250We have 3 beds units available for rent
  amenities bathrooms bedrooms currency fee has_photo pets_allowed ⋯
1 NA        1.0       1        USD      No  Thumbnail Cats         ⋯
2 NA        1.5       3        USD      No  Thumbnail Cats,Dogs    ⋯
  price_display price_type square_feet address            cityname      state
1 2195          Monthly     542        507  509 Esplanade Redondo Beach CA
2 1250          Monthly    1500        146 Lochview Dr    Newport News  VA
  latitude longitude source    time
1 33.8520  -118.3759 RentLingo 1577360355
2 37.0867   -76.4941 RentLingo 1577360340

In [3]:
distinct(df, category)

   category
1  housing/rent/apartment
2  housing/rent/home
3  housing/rent/short_term
4  Gym
5  housing/rent
6  Parking,Patio/Deck
7  housing/rent/condo
8  housing/rent/other
9  housing/rent/commercial/retail
10 2

In [4]:
count(distinct(df, source))

  n
1 26

In [14]:
filter(df, time > 0) %>%
summarize(min_ido = as_datetime(min(time)),
          atlag_ido = as_datetime(mean(time)),
          max_ido = as_datetime(max(time)))

  min_ido             atlag_ido           max_ido
1 2018-12-07 09:20:18 2019-06-04 23:08:14 2019-12-26 20:17:05